name: Build LicheeRV Nano Image

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - boards: licheervnano
            variant: e
            storage: sd
            archs: riscv

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build local builder image
        run: |
          docker build -t sophgo-builder:local -f ./scripts/Dockerfile .

      - name: Build images
        run: |
          mkdir -p images
          docker run --privileged --rm \
            -v "${{ github.workspace }}/images:/output" \
            -v "${{ github.workspace }}/configs:/configs" \
            sophgo-builder:local \
            make ARCH=${{ matrix.archs }} BOARD=${{ matrix.boards }} VARIANT=${{ matrix.variant }} STORAGE_TYPE=${{ matrix.storage }} GIT_REF=${{ github.ref_name }} image

          sudo chmod -R 777 images

      - name: Pack
        run: |
          cd images
          ls -lah
          if compgen -G "*.deb" > /dev/null; then
            tar czvf ${{ matrix.boards }}-${{ matrix.variant }}-${{ matrix.storage }}_debs.tar.gz *.deb
            rm -f *.deb
          fi

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: image-files-${{ matrix.boards }}-${{ matrix.variant }}-${{ matrix.storage }}
          path: images/*

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [build-image]
    permissions:
      contents: write

    steps:
      - name: Download firmware
        uses: actions/download-artifact@v4

      - name: List images
        run: |
          ls -lah
          ls -lah image-files-*/

      - name: Publish artifacts
        uses: softprops/action-gh-release@v2
        with:
          append_body: true
          files: |
            image-files-*/*
